const menu=[
{name:"Set Dosa",price:90,image:"set-dosa-luxury.png",desc:"Soft dosas with chutney and sambar."},
{name:"Bisi Bele Bath",price:120,image:"bisi-bele-bath-luxury.png",desc:"Karnataka rice-lentil comfort bowl."},
{name:"Lemon Rice",price:80,image:"lemon-rice-luxury.png",desc:"Bright rice with peanuts and curry leaves."},
{name:"Masala Dosa",price:95,image:"masala-dosa-luxury.png",desc:"Crisp dosa with potato masala."},
{name:"Paneer Butter Masala",price:180,image:"paneer-butter-masala-luxury.png",desc:"Paneer in silky tomato-butter gravy."},
{name:"Lassi",price:60,image:"lassi-luxury.png",desc:"Chilled creamy yogurt drink."}
];
const credentials={customer:{id:"customer@npl.com",password:"customer123"},admin:{id:"admin@npl.com",password:"admin123"}};
const ownerEmail="namanapreethi.lounge@gmail.com";
const funnyQuotes=["Diet starts tomorrow. Today we feast.","Our dosa is crispier than Monday morning excuses.","Calories do not count inside a luxury lounge.","Good memories are best served with extra chutney.","If happiness had a plate, it would ask for seconds.","Bisi Bele Bath: proof that comfort can be royal.","Life is short. Order the extra lassi."];
const heroFunnyHeadlines=["Our dosa is so crisp, even your attendance shortage will forget its sadness.","Come hungry. Leave royal. Blame the extra chutney.","When life gives you deadlines, we give you Masala Dosa.","Food so good, your diet will politely resign.","One bite here and your Monday becomes a festival."];
const welcomeQuotes=["Good memories are best served hot.","Five years of taste, one lounge full of stories.","From Karnataka kitchens to luxury tables.","Grand opening in Bengaluru: 19.06.2026.","Authentic South Indian taste, served with modern elegance."];
const qs=(s,p=document)=>p.querySelector(s),qsa=(s,p=document)=>[...p.querySelectorAll(s)],money=n=>`\u20b9${Math.round(n)}`,gst=s=>Math.round(s*.05);
const defaults={cart:[],orders:[],reservations:[],customers:[],auth:{customer:false,admin:false},lastReceipt:null,lastBillReceipt:null,billItems:[{name:"Masala Dosa",price:95,qty:1},{name:"Paneer Butter Masala",price:180,qty:1}]};
const state=Object.assign(defaults,JSON.parse(localStorage.getItem("npl-app-state")||"null")||{});state.auth=Object.assign({customer:false,admin:false},state.auth||{});state.customers||=[];state.cart||=[];state.orders||=[];state.reservations||=[];state.billItems||=[];
let autoLocationRequested=false;
function save(){localStorage.setItem("npl-app-state",JSON.stringify(state));renderAll();}
function setView(view){qsa(".view").forEach(x=>x.classList.toggle("active",x.id===view));qsa("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));const titles={home:"Namana & Preethi's Lounge",customer:"Customer Ordering Portal",reservation:"Table Reservation System",admin:"Admin Management Suite",billing:"Namana & Preethi's Lounge Billing"};qs("#viewTitle").textContent=titles[view]||titles.home;document.body.classList.remove("menu-open");renderAuth();if(view==="customer")requestGoogleLocation(true);} 
document.addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)setView(b.dataset.view);});qs(".mobile-menu")?.addEventListener("click",()=>document.body.classList.toggle("menu-open"));
function renderCustomerMenu(){qs("#customerMenu").innerHTML=menu.map(i=>`<article class="food-card"><img src="${i.image}" alt="${i.name}"><div><h3>${i.name}</h3><p>${i.desc}</p><button class="gold-btn" data-add-cart="${i.name}"><i data-lucide="plus"></i>Add ${money(i.price)}</button></div></article>`).join("");}
qsa("[data-login-form]").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();const role=form.dataset.loginForm,data=Object.fromEntries(new FormData(form)),msg=qs(`[data-login-message="${role}"]`),registered=role==="customer"?state.customers.find(c=>c.email.toLowerCase()===data.loginId.trim().toLowerCase()&&c.password===data.password):null;if((data.loginId.trim()===credentials[role].id&&data.password===credentials[role].password)||registered){state.auth[role]=true;msg.textContent=registered?`Login successful. Welcome ${registered.name}.`:"Login successful. Welcome to Namana & Preethi's Lounge.";save();return;}msg.textContent="Wrong login ID or password. Please use the locked demo credentials.";}));
qs("#customerRegisterForm")?.addEventListener("submit",e=>{e.preventDefault();const form=e.currentTarget,msg=qs("#registerMessage");if(!form.reportValidity())return;const d=Object.fromEntries(new FormData(form));if(d.password!==d.confirmPassword){msg.textContent="Password and confirm password do not match.";return;}if(state.customers.some(c=>c.email.toLowerCase()===d.email.trim().toLowerCase()||c.mobile===d.mobile.trim())){msg.textContent="This email or mobile number is already registered. Please login with your registered details.";return;}const customer={id:`CUS-${Date.now().toString().slice(-5)}`,name:d.name.trim(),mobile:d.mobile.trim(),email:d.email.trim(),password:d.password,message:d.message.trim(),time:new Date().toLocaleString()};state.customers.unshift(customer);state.auth.customer=true;save();const subject=encodeURIComponent(`New customer registration - ${customer.name}`);const body=encodeURIComponent([`Customer ID: ${customer.id}`,`Name: ${customer.name}`,`Mobile: ${customer.mobile}`,`Email: ${customer.email}`,`Issue / Message: ${customer.message}`,"","Security note: customer password is not sent by email. It is created for login in this demo."].join("\n"));msg.innerHTML=`Registration successful. Your customer login is your email ID. <a href="mailto:${ownerEmail}?subject=${subject}&body=${body}">Send issue message to lounge email</a>`;form.reset();});
function renderAuth(){const cu=!!state.auth.customer,au=!!state.auth.admin;qsa('[data-lock="customer"]').forEach(x=>x.classList.toggle("active",!cu));qsa('[data-content="customer"]').forEach(x=>x.classList.toggle("hidden",!cu));qsa('[data-lock="admin"],[data-lock="billing"]').forEach(x=>x.classList.toggle("active",!au));qsa('[data-content="admin"],[data-content="billing"]').forEach(x=>x.classList.toggle("hidden",!au));}
qs("#customerMenu")?.addEventListener("click",e=>{const b=e.target.closest("[data-add-cart]");if(!b)return;const item=menu.find(i=>i.name===b.dataset.addCart),ex=state.cart.find(i=>i.name===item.name);ex?ex.qty++:state.cart.push({name:item.name,price:item.price,qty:1});save();});
function requestGoogleLocation(isAuto=false){const field=qs('#deliveryForm [name="location"]'),link=qs("#openGoogleMaps"),msg=qs("#orderMessage");if(!field||!msg)return;if(isAuto){if(autoLocationRequested||field.value.trim())return;autoLocationRequested=true;}if(!navigator.geolocation){msg.textContent="Google location is not supported in this browser. Please paste your Google Maps link or type your address.";return;}msg.textContent=isAuto?"Please allow location permission so we can auto-detect your delivery location.":"Getting your Google location. Please allow location permission.";navigator.geolocation.getCurrentPosition(pos=>{const {latitude,longitude}=pos.coords,url=`https://www.google.com/maps?q=${latitude},${longitude}`;field.value=url;link.href=url;link.textContent="Open Your Google Location";msg.textContent="Google location added successfully. You can now confirm your order.";},()=>{msg.textContent="Location permission was blocked. Open Google Maps, copy your location link, and paste it in the delivery location box.";link.href="https://www.google.com/maps";link.textContent="Open Google Maps";},{enableHighAccuracy:true,timeout:10000,maximumAge:0});}
qs("#useGoogleLocation")?.addEventListener("click",()=>requestGoogleLocation(false));
function renderCart(){qs("#cartItems").innerHTML=state.cart.length?state.cart.map(i=>`<div class="line-item"><span>${i.name} x ${i.qty}</span><strong>${money(i.price*i.qty)}</strong></div>`).join(""):`<p class="eyebrow">Cart is empty</p>`;const sub=state.cart.reduce((s,i)=>s+i.price*i.qty,0),tax=gst(sub);qs("#cartSubtotal").textContent=money(sub);qs("#cartGst").textContent=money(tax);qs("#cartTotal").textContent=money(sub+tax);renderCustomerReceipt();}
qs("#checkoutBtn")?.addEventListener("click",()=>{if(!state.cart.length)return;const form=qs("#deliveryForm");if(!form.reportValidity())return;const d=Object.fromEntries(new FormData(form)),sub=state.cart.reduce((s,i)=>s+i.price*i.qty,0),tax=gst(sub),receipt={id:`ORD-${Date.now().toString().slice(-5)}`,type:"Online Food Order",customer:d.customerName.trim(),mobile:d.mobile.trim(),location:d.location.trim(),items:[...state.cart],subtotal:sub,gst:tax,total:sub+tax,time:new Date().toLocaleString()};state.orders.unshift(receipt);state.lastReceipt=receipt;state.cart=[];form.reset();save();qs("#orderMessage").textContent="Thank you for ordering from Namana & Preethi's Lounge. Your receipt is confirmed and our lounge team is preparing your food.";});
function renderCustomerReceipt(){const r=state.lastReceipt,card=qs("#customerReceipt");if(!r){card?.classList.add("hidden");return;}card.classList.remove("hidden");qs("#receiptId").textContent=r.id;qs("#receiptDetails").textContent=`${r.customer}, your order total is ${money(r.total)}. Delivery location: ${r.location}. Thank you for ordering.`;}
qs("#reservationForm")?.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));state.reservations.unshift({...d,id:`RSV-${Date.now().toString().slice(-5)}`});e.currentTarget.reset();save();});
function renderReservations(){qs("#reservationList").innerHTML=state.reservations.length?state.reservations.map(r=>`<div class="record"><span><strong>${r.name}</strong><br>${r.mobile} | ${r.date} ${r.time} | ${r.guests} guests</span><b>${r.occasion}</b></div>`).join(""):`<p class="eyebrow">No reservations yet</p>`;}
function renderOrders(){qs("#orderList").innerHTML=state.orders.length?state.orders.map(o=>`<div class="record"><span><strong>${o.id}</strong> ${o.type?`<em>${o.type}</em>`:""}<br>${o.customer||""} | ${o.mobile||""}<br>${o.location?`Location: ${o.location}<br>`:""}${o.items.map(i=>`${i.name} x ${i.qty}`).join(", ")}<br>${o.time}</span><b>${money(o.total)}</b></div>`).join(""):`<p class="eyebrow">No orders yet</p>`;}
function renderMetrics(){const rev=state.orders.reduce((s,o)=>s+o.total,0);["metricOrders","adminOrders"].forEach(id=>qs(`#${id}`).textContent=state.orders.length);["metricReservations","adminBookings"].forEach(id=>qs(`#${id}`).textContent=state.reservations.length);["metricRevenue","adminRevenue"].forEach(id=>qs(`#${id}`).textContent=money(rev));}
function renderBill(){qs("#billRows").innerHTML=state.billItems.map(i=>`<div class="line-item"><span>${i.name} x ${i.qty}</span><strong>${money(i.price*i.qty)}</strong></div>`).join("");const sub=state.billItems.reduce((s,i)=>s+i.price*i.qty,0),tax=gst(sub);qs("#billSubtotal").textContent=money(sub);qs("#billGst").textContent=money(tax);qs("#billTotal").textContent=money(sub+tax);if(state.lastBillReceipt){qs("#billReceiptMeta").textContent=`${state.lastBillReceipt.id} | ${state.lastBillReceipt.time}`;qs("#billConfirm").textContent=`Receipt confirmed for ${state.lastBillReceipt.customer}. Total paid: ${money(state.lastBillReceipt.total)}. Thank you for dining with us.`;}else{qs("#billReceiptMeta").textContent="Receipt preview ready";qs("#billConfirm").textContent="Receipt confirmation will appear here after billing.";}}
qs("#addBillItem")?.addEventListener("click",()=>{const form=qs("#billingForm"),d=Object.fromEntries(new FormData(form)),name=d.item.trim(),price=Number(d.price),qty=Math.max(Number(d.qty||1),1);if(!name||!price)return;state.billItems.push({name,price,qty});form.elements.item.value="";form.elements.price.value="";form.elements.qty.value="1";save();});
qs("#saveBill")?.addEventListener("click",()=>{if(!state.billItems.length)return;const form=qs("#billingForm"),d=Object.fromEntries(new FormData(form)),sub=state.billItems.reduce((s,i)=>s+i.price*i.qty,0),tax=gst(sub),r={id:`BILL-${Date.now().toString().slice(-5)}`,type:"Counter Billing Receipt",customer:d.customer.trim()||"Guest Customer",mobile:d.mobile.trim(),items:[...state.billItems],subtotal:sub,gst:tax,total:sub+tax,time:new Date().toLocaleString()};state.orders.unshift(r);state.lastBillReceipt=r;state.billItems=[];save();});
qs("#resetDemo")?.addEventListener("click",()=>{localStorage.removeItem("npl-app-state");location.reload();});
function applyTheme(mode){const light=mode==="light";document.body.classList.toggle("light-mode",light);const t=qs("#themeToggle");if(t)t.innerHTML=`<i data-lucide="${light?"moon":"sun"}"></i><span>${light?"Dark Mode":"White Mode"}</span>`;localStorage.setItem("npl-theme",light?"light":"dark");if(window.lucide)window.lucide.createIcons();}
qs("#themeToggle")?.addEventListener("click",()=>applyTheme(document.body.classList.contains("light-mode")?"dark":"light"));
function startQuoteSlides(){let i=0;const tick=()=>{qs("#funnyQuote").textContent=funnyQuotes[i%funnyQuotes.length];qs("#heroFunnyHeadline").textContent=heroFunnyHeadlines[i%heroFunnyHeadlines.length];qs("#welcomeQuote").textContent=welcomeQuotes[i%welcomeQuotes.length];i++;};tick();setInterval(tick,4000);}
function startWelcome(){const screen=qs("#welcomeScreen"),timer=qs("#welcomeTimer"),enter=qs("#enterApp");let s=10;const close=()=>{screen.classList.add("hide");setTimeout(()=>screen.remove(),650);};const tick=setInterval(()=>{s--;if(timer)timer.textContent=s;if(s<=0){clearInterval(tick);close();}},1000);enter?.addEventListener("click",()=>{clearInterval(tick);close();});}
function renderAll(){renderCustomerMenu();renderCart();renderReservations();renderOrders();renderMetrics();renderBill();renderAuth();if(window.lucide)window.lucide.createIcons();}
renderAll();applyTheme(localStorage.getItem("npl-theme")||"dark");startQuoteSlides();startWelcome();setView("home");
